import {
  typography,
  nativeRadius,
  nativeSpacing,
  nativeFontSize,
} from '@qr/ui-tokens';

export const theme = {
  build: '2026.07.09-v4',
  colors: {
    primary: '#5B5BD6',
    primaryDark: '#4343B8',
    primaryLight: '#EDEDFC',
    primarySoft: '#F5F5FF',
    accent: '#0EA5E9',
    background: '#F4F6FB',
    surface: '#FFFFFF',
    surfaceHover: '#FAFBFE',
    text: '#111827',
    textSecondary: '#4B5563',
    textMuted: '#9CA3AF',
    textSubtle: '#9CA3AF',
    border: '#E5E7EB',
    borderLight: '#F3F4F6',
    success: '#059669',
    successBg: '#ECFDF5',
    warning: '#D97706',
    warningBg: '#FFFBEB',
    error: '#DC2626',
    errorBg: '#FEF2F2',
    info: '#0284C7',
    infoBg: '#F0F9FF',
    drawerBg: '#FFFFFF',
    drawerBorder: '#F3F4F6',
    drawerActive: '#F5F5FF',
    overlay: 'rgba(17,24,39,0.4)',
    gradientHero: ['#5B5BD6', '#7C6CF0', '#5B8DEF'] as const,
    gradientButton: ['#5B5BD6', '#6B6BE0'] as const,
    gradientAuroraA: ['#C7D2FE', '#A5B4FC', 'transparent'] as const,
    gradientAuroraB: ['#BAE6FD', '#93C5FD', 'transparent'] as const,
  },
  typography,
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    '2xl': 24,
    full: 999,
  },
  spacing: nativeSpacing,
  fontSize: nativeFontSize,
  shadow: {
    sm: {
      shadowColor: '#1F2937',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 2,
    },
    md: {
      shadowColor: '#1F2937',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.08,
      shadowRadius: 16,
      elevation: 4,
    },
    lg: {
      shadowColor: '#5B5BD6',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.15,
      shadowRadius: 24,
      elevation: 8,
    },
  },
};

export type Theme = typeof theme;
